name = "titanic"
uuid = "73d388ad-17bb-4b2b-a9eb-04bfbf14bd40"
authors = ["Jakub Rada <radajak5@fel.cvut.cz>"]
version = "1.0.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
